### ISSUE TITLE
Docs 

### ISSUE THREAD

**Issue by tadejoremuz** [accubits/smart-kyc#1]
Hi, 
i wanted to test smart-kyc but there is no documentation for initial setup/config for users to be able to test your smart-kyc. I've deployed it to my local environment but since init only creates mysql tables without entries i was not able to access admin area or anything really beside login area. Is any chance for you to post initial settings to test smart-kyc - like default admin account entry for mysql etc. 

best regards, 
Tadej

**Comment by dittops** [comment]
Sure will create a script and upload that. To view the admin features you can go through the demo account here.

http://52.220.41.10/smart-kyc/admin/
username: admin@admin.com
pass: admin

**Comment by tadejoremuz** [comment]
Hi, 
any progress maybe with the script :) ?

**Comment by Easampson** [comment]
Hey,
I'm also interested in deploying the site and visited the address you posted. Although the login credentials provided were invalid. Any input would be appreciated.

Much thanks,
Ed

**Comment by kris911** [comment]
Hi, same here those credentials don't work for me either for demo

**Comment by dittops** [comment]
Hey Guys, please check now.

**Comment by kris911** [comment]
@dittops thank you, I am able to log in now but stuck on the load screen with spinning 'S'

**Comment by dittops** [comment]
There were some changes in the DB after the update. I have cleared the data. Now it should be working fine.

**Comment by philgrim2** [comment]
I'm able to use the test site provided above, but I can't get my own instance to work.  I have gotten the database to initialize, and I can view the site, but I can't register a user.  There isn't much of an error message.  I'm running on Ubuntu 16.04, with the standard mysql, php7.0, and nginx.  

I'd love to use this software for our upcoming ICO, but for that I need to get it working.  Any help, advice, or documentation would be welcome.

**Comment by dittops** [comment]
@philgrim2 have you updated the DB details in the config file?

I have added very minimal installation steps in this page https://github.com/accubits/smart-kyc/wiki/Application-Installation

**Comment by icryptix** [comment]
In file /js/config.js line 1, you need to edit this and replace it with your own website's URL:

var ServerApi =     'http://smartkyc.ml';

Didn't see that in your instructions.

**Comment by dittops** [comment]
Hi @icryptix , thanks for pointing that out. I have updated the doc with that. 

Regarding the registration, I just tried a new registration and it was working fine.

**Comment by alertor-1** [comment]
New user reg not working either

**Comment by dittops** [comment]
> http://52.220.41.10/smart-kyc/admin/
> username: [admin@admin.com](mailto:admin@admin.com)
> pass: admin
> 
> This user/pass no longer working.


I have updated the credentials. Please try again with the same details.

**Comment by dittops** [comment]
> Has this been resolved?
> 
> I recently setup smartkyc and nothing seems to work.
> 
> * Login credentials aren't working
> * registration is working

Registration is working now. Let me know if you still face any issues.

**Comment by kmoragas** [comment]
Not working again :(. I'm getting internal server error
