### ISSUE TITLE
Smart-KYC for Android (Java)

### ISSUE THREAD

**Issue by CarlosRoldanx** [accubits/smart-kyc#2]
Hey guys!!

I was wondering if there is any way I can adapt this repository to a java project (Android) in order to provide a KYC for every user when signing up.

Are there any **APIs or documentation** to adapt this repository? 

Thanks guys! Keep the work up:raised_hands:

**Comment by dittops** [comment]
Hi @CarlosRoldanx , this application is completely REST API based. So you can surely deploy this on a server and use the API's in Android.
