### ISSUE TITLE
User registration does not work at all

### ISSUE THREAD

**Issue by locolab** [accubits/smart-kyc#4]
On the demo site http://52.220.41.10/smart-kyc/ new user registration is getting a 500 server error.

I see that new users are being created in the admin backend but none of the accounts I've tried have received an email verification email. Thus I cannot log in and try any features. Really want to use this!

<img width="1237" alt="screen shot 2018-06-17 at 17 43 27" src="https://user-images.githubusercontent.com/2372500/41512421-0b4bc4dc-7256-11e8-95db-2c1088a7d3e5.png">

**Comment by dittops** [comment]
Please try again now, you should be able to register with a new email.
